# Generated by Django 3.0.5 on 2021-05-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='btc_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='usd_balance',
            field=models.FloatField(default=0),
        ),
    ]
